name: i18n_extension_importer
description: Text Importer for i18n_extension
version: 0.0.6
repository: https://github.com/c0dezli/i18n_extension_importer

environment:
  sdk: '>=3.1.5 <4.0.0'

platforms:
    android:
    ios:
    macos:
    windows:
    web:

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  gettext_parser: any
  equatable: any
  analyzer: any
  args: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
